package main

import (
 "fmt"
 "strings"
 "github.com/skycoin/skycoin/src/cipher"
 "os"
 "bufio"
 "math/rand"
)

var (
 // This is a dev seed and address generated by the Skycoin desktop wallet. There are no funds here.
 testSeed    = "legal slim uncover profit circle slush donor gift marriage ill exact"  // add test seed string here
 testAddress = "22rP6UB5qojB9BT8kt9eBAfNQCfkicyg6EU" // add test wallet address here
)

func main() {
	wordmap := WordCount(testSeed)
	fmt.Println("Word count", len(wordmap))
		if len(wordmap) != 12 {
			fmt.Println("Not equal to 12") 
		// add in words to make seed 12. 
		fmt.Println("addSeedWords: ", addSeedWords(1))
		
	}
	// fmt.Println("Starting")
	// defer fmt.Println("Finished")
 fmt.Println("Seed:    ", testSeed)
 fmt.Println("Address: ", recoverWalletAddressFromSeed(testSeed))
 
}

func addSeedWords(n int) string {
	random := LinesInFile("Wordlist.txt")
	rand := rand.Intn(2047)
	fmt.Println("randomnumber: ", rand)
	word := random[rand]
	return word
}

func recoverWalletAddressFromSeed(seed string) string {
 // Generate the first address from the seed
 pk,_,_ := cipher.GenerateDeterministicKeyPair([]byte(seed))
				
 //pk, _ := cipher.GenerateDeterministicKeyPair([]byte(seed))
 addr := cipher.AddressFromPubKey(pk)
 return addr.String()
}

func WordCount(s string) map[string]int { 
    words := strings.Fields(s) 
    m := make(map[string]int) 
    for _, word := range words { 
        m[word] += 1 
    } 
    return m 
}


func LinesInFile(fileName string) []string {
    f, _ := os.Open(fileName)
    // Create new Scanner.
    scanner := bufio.NewScanner(f)
    result := []string{}
    // Use Scan.
    for scanner.Scan() {
        line := scanner.Text()
        // Append line to result.
        result = append(result, line)
    }
    return result
}
