package main

import (
 "fmt"

 "github.com/skycoin/skycoin/src/cipher"
)

var (
 // This is a dev seed and address generated by the Skycoin desktop wallet. There are no funds here.
 testSeed    = "legal slim uncover profit circle slush slow donor gift marriage ill exact"  // add test seed string here
 testAddress = "22rP6UB5qojB9BT8kt9eBAfNQCfkicyg6EU" // add test wallet address here
)

func main() {
 fmt.Println("Starting")
 defer fmt.Println("Finished")
 fmt.Println("Seed:    ", testSeed)
 fmt.Println("Address: ", recoverWalletAddressFromSeed(testSeed))
}

func recoverWalletAddressFromSeed(seed string) string {
 // Generate the first address from the seed
 pk, _ := cipher.GenerateDeterministicKeyPair([]byte(seed))
 addr := cipher.AddressFromPubKey(pk)
 return addr.String()
}
